# 1

In [5]:
import numpy as np
a = [0,1,2,3,4]
b = [9,8,7,6,5]
A = np.array(a)
B = np.array(b)
A+B

array([9, 9, 9, 9, 9])

# 2

###  1

In [51]:
def pf():
    X1=[]
    for i in range(len(a)):
        X1.append(a[i]**2 + b[i]**3)
    return X1    
pf()        

[729, 513, 347, 225, 141]

In [52]:
def pf1():
    X2 =[]
    for i,n in zip(a,b):
        X2.append(i**2+n**3)
    return X2
pf1()

[729, 513, 347, 225, 141]

### 2

In [45]:
hs = lambda x,y:x**2+y**3
list(map(hs,a,b))

[729, 513, 347, 225, 141]

### 3

In [15]:
A**2+B**3

array([729, 513, 347, 225, 141], dtype=int32)

# 3

In [60]:
arr = np.full((2,3,4),1)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [59]:
arr.shape

(2, 3, 4)

# 4

In [74]:
np.logspace(0,5,6,base=2)

array([ 1.,  2.,  4.,  8., 16., 32.])

# 5

In [75]:
arr5 = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a=arr5[[0,1,2],[2]]

array([3, 6, 9])

In [80]:
a=np.array([13,16,19])

In [81]:
arr5[[0,1,2],[2]] = a

In [82]:
arr5

array([[ 1,  2, 13],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [88]:
arr5_2 = (np.arange(1,10)).reshape(3,3)

In [93]:
arr5_2[:,2]=[13,16,19]

In [94]:
arr5_2

array([[ 1,  2, 13],
       [ 4,  5, 16],
       [ 7,  8, 19]])

# 6

In [95]:
arr6 = np.arange(24).reshape(2,3,4)

In [96]:
arr6[0,1,2]

6

# 7

In [97]:
arr6[-1,-2,-3]

17

# 8

In [98]:
arr6

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [100]:
arr6[:,1:,0:2]

array([[[ 4,  5],
        [ 8,  9]],

       [[16, 17],
        [20, 21]]])

In [105]:
arr6[:,1:,[0,1]]

array([[[ 4,  5],
        [ 8,  9]],

       [[16, 17],
        [20, 21]]])

In [104]:
arr6[:,:,[0,2]]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [107]:
arr6[:,:,::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

# 思考题

In [108]:
arrs=np.full((8,8),1)

In [109]:
arrs

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [110]:
arrs[::2,1::2]=0

In [112]:
arrs[1::2,::2]=0

In [113]:
arrs

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [135]:
for i in arrs:
    for j in i:
        if j == 1:
            print("■",end="")
            
        else:
            print("□",end="")
    print("\n")    

■□■□■□■□

□■□■□■□■

■□■□■□■□

□■□■□■□■

■□■□■□■□

□■□■□■□■

■□■□■□■□

□■□■□■□■

