In [83]:
import numpy as np
import random

In [15]:
arr = np.full((6,6),0)
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
arr[[0,5],]=1
arr[:,[0,5]]=1
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

# 1

In [105]:
arr = np.full((6,6),0)
arr[[0,5],]=1
arr[:,[0,5]]=1
arr = np.matrix(arr)
arr

matrix([[1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1, 1]])

# 2

In [39]:
arr2 = np.full((2,2),5)
mat1=np.matrix(arr2)
mat1

matrix([[5, 5],
        [5, 5]])

In [38]:
arr2_1 = np.arange(4).reshape(2,2)
mat2=np.matrix(arr2_1)
mat2

matrix([[0, 1],
        [2, 3]])

In [43]:
mat1*mat2                                                           

matrix([[10, 20],
        [10, 20]])

# 3

In [80]:
a = np.arange(24).reshape(4,6)
a = np.matrix(a)
a

matrix([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [81]:
b = np.arange(6).reshape(1,6)
b = np.matrix(b)
b

matrix([[0, 1, 2, 3, 4, 5]])

In [111]:
shape = a+b

In [112]:
shape

matrix([[ 0,  2,  4,  6,  8, 10],
        [ 6,  8, 10, 12, 14, 16],
        [12, 14, 16, 18, 20, 22],
        [18, 20, 22, 24, 26, 28]])

# 4

In [79]:
np.loadtxt(r'D:\新建文件夹\iris_sepal_length.csv', delimiter=',' , unpack=True)

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [109]:
iris = np.loadtxt(r'D:\新建文件夹\iris_sepal_length.csv', delimiter=',' , unpack=True)

In [110]:
iris

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [113]:
iris.sort(axis=0)

In [ ]:
iris.sort(axis=1)

In [114]:
iris

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [115]:
np.unique(iris)

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [116]:
np.sum(iris)

876.5

In [117]:
np.mean(iris)

5.843333333333334

In [118]:
np.std(iris)

0.8253012917851409

In [119]:
np.var(iris)

0.6811222222222223

In [120]:
np.min(iris)

4.3

In [121]:
np.max(iris)

7.9

In [122]:
np.cumsum(iris)

array([  4.3,   8.7,  13.1,  17.5,  22. ,  26.6,  31.2,  35.8,  40.4,
        45.1,  49.8,  54.6,  59.4,  64.2,  69. ,  73.8,  78.7,  83.6,
        88.5,  93.4,  98.3, 103.2, 108.2, 113.2, 118.2, 123.2, 128.2,
       133.2, 138.2, 143.2, 148.2, 153.2, 158.3, 163.4, 168.5, 173.6,
       178.7, 183.8, 188.9, 194. , 199.1, 204.3, 209.5, 214.7, 219.9,
       225.2, 230.6, 236. , 241.4, 246.8, 252.2, 257.6, 263.1, 268.6,
       274.1, 279.6, 285.1, 290.6, 296.1, 301.7, 307.3, 312.9, 318.5,
       324.1, 329.7, 335.4, 341.1, 346.8, 352.5, 358.2, 363.9, 369.6,
       375.3, 381.1, 386.9, 392.7, 398.5, 404.3, 410.1, 415.9, 421.8,
       427.7, 433.6, 439.6, 445.6, 451.6, 457.6, 463.6, 469.6, 475.7,
       481.8, 487.9, 494. , 500.1, 506.2, 512.4, 518.6, 524.8, 531. ,
       537.3, 543.6, 549.9, 556.2, 562.5, 568.8, 575.1, 581.4, 587.7,
       594.1, 600.5, 606.9, 613.3, 619.7, 626.1, 632.5, 639. , 645.5,
       652. , 658.5, 665. , 671.6, 678.2, 684.9, 691.6, 698.3, 705. ,
       711.7, 718.4,

In [123]:
np.cumprod(iris)

array([4.30000000e+000, 1.89200000e+001, 8.32480000e+001, 3.66291200e+002,
       1.64831040e+003, 7.58222784e+003, 3.48782481e+004, 1.60439941e+005,
       7.38023729e+005, 3.46871153e+006, 1.63029442e+007, 7.82541320e+007,
       3.75619834e+008, 1.80297520e+009, 8.65428097e+009, 4.15405487e+010,
       2.03548688e+011, 9.97388573e+011, 4.88720401e+012, 2.39472996e+013,
       1.17341768e+014, 5.74974664e+014, 2.87487332e+015, 1.43743666e+016,
       7.18718331e+016, 3.59359165e+017, 1.79679583e+018, 8.98397913e+018,
       4.49198957e+019, 2.24599478e+020, 1.12299739e+021, 5.61498696e+021,
       2.86364335e+022, 1.46045811e+023, 7.44833635e+023, 3.79865154e+024,
       1.93731228e+025, 9.88029265e+025, 5.03894925e+026, 2.56986412e+027,
       1.31063070e+028, 6.81527964e+028, 3.54394541e+029, 1.84285162e+030,
       9.58282840e+030, 5.07889905e+031, 2.74260549e+032, 1.48100696e+033,
       7.99743760e+033, 4.31861631e+034, 2.33205280e+035, 1.25930851e+036,
       6.92619683e+036, 3