In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel(r"E:\大二下\数据分析\灰色预测\gm.xlsx")
df

时间      人口
0   1985  101.02
1   1986  102.19
2   1987  106.50
3   1988  111.08
4   1989  113.28
5   1990  115.97
6   1991  118.02
7   1992  119.99
8   1993  123.23
9   1994  132.37
10  1995  135.95
11  1996  138.82
12  1997  143.18
13  1998  146.51
14  1999  151.54
15  2000  159.47

In [4]:
k = df['时间']
k

0     1985
1     1986
2     1987
3     1988
4     1989
5     1990
6     1991
7     1992
8     1993
9     1994
10    1995
11    1996
12    1997
13    1998
14    1999
15    2000
Name: 时间, dtype: int64

In [5]:
[i for i in k]

[1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000]

In [6]:
lj = df['人口'].expanding(1).sum()
lj

0      101.02
1      203.21
2      309.71
3      420.79
4      534.07
5      650.04
6      768.06
7      888.05
8     1011.28
9     1143.65
10    1279.60
11    1418.42
12    1561.60
13    1708.11
14    1859.65
15    2019.12
Name: 人口, dtype: float64

In [53]:
-df['人口'].expanding(1).sum().rolling(2,2).mean()[1:].values

array([ -152.115,  -256.46 ,  -365.25 ,  -477.43 ,  -592.055,  -709.05 ,
        -828.055,  -949.665, -1077.465, -1211.625, -1349.01 , -1490.01 ,
       -1634.855, -1783.88 , -1939.385])

In [7]:
-lj.rolling(2,2).mean()[1:]

1     -152.115
2     -256.460
3     -365.250
4     -477.430
5     -592.055
6     -709.050
7     -828.055
8     -949.665
9    -1077.465
10   -1211.625
11   -1349.010
12   -1490.010
13   -1634.855
14   -1783.880
15   -1939.385
Name: 人口, dtype: float64

In [8]:
Yn = df['人口'][1:].values

In [9]:
BT = np.vstack((-lj.rolling(2,2).mean()[1:].values,np.array([1 for _ in range(len(lj)-1)])))
BT

array([[-1.521150e+02, -2.564600e+02, -3.652500e+02, -4.774300e+02,
        -5.920550e+02, -7.090500e+02, -8.280550e+02, -9.496650e+02,
        -1.077465e+03, -1.211625e+03, -1.349010e+03, -1.490010e+03,
        -1.634855e+03, -1.783880e+03, -1.939385e+03],
       [ 1.000000e+00,  1.000000e+00,  1.000000e+00,  1.000000e+00,
         1.000000e+00,  1.000000e+00,  1.000000e+00,  1.000000e+00,
         1.000000e+00,  1.000000e+00,  1.000000e+00,  1.000000e+00,
         1.000000e+00,  1.000000e+00,  1.000000e+00]])

In [10]:
np.matrix(np.dot(BT,BT.T)).I

matrix([[2.20200072e-07, 2.17503502e-04],
        [2.17503502e-04, 2.81506621e-01]])

In [11]:
np.dot(BT,Yn)

array([-2.03332027e+06,  1.91810000e+03])

In [12]:
a_ = np.dot(np.matrix(np.dot(BT,BT.T)).I,np.dot(BT,Yn))
a_

matrix([[-3.05438022e-02,  9.77035705e+01]])

In [13]:
a = a_[[0],[0]]

In [14]:
u=a_[[0],[1]]

In [15]:
u/a

matrix([[-3198.80183454]])

In [43]:
x2=[]
for i in k:
    x2.append(np.float(((lj[0]-u/a)*np.exp(-a*(i - 1985))+u/a)))
x2

[101.01999999999998,
 203.3641385063661,
 308.88248556453027,
 417.67348941078035,
 529.8386516583541,
 645.4826219980778,
 764.7132958361494,
 887.6419149601643,
 1014.3831713272957,
 1145.0553140714837,
 1279.7802598294438,
 1418.6837064884467,
 1561.8952504620001,
 1709.548507602829,
 1861.78123786598,
 2018.7354738383701]

In [50]:
yc = [] 
for m in range(1,len(x2)):
    yc.append(x2[m]-x2[m-1])
yc

[102.34413850636611,
 105.51834705816418,
 108.79100384625008,
 112.16516224757379,
 115.64397033972364,
 119.23067383807165,
 122.92861912401486,
 126.74125636713143,
 130.67214274418802,
 134.72494575796009,
 138.90344665900284,
 143.2115439735535,
 147.65325714082883,
 152.2327302631511,
 156.95423597239005]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

-3198.8018345410037

matrix([[1.58115728]])

[[3299.82183454]]


1.0